### ISSUE TITLE
getting data issue

### ISSUE THREAD

**Issue by lengx03** [EntireNewsProject/Python-Backend#4]
You must `download()` an article first!

Traceback (most recent call last):

 File "C:/Users/leng/Documents/Project/scrapNrequest.py", line 35, in <module>

   live_data = scrap_article('cnn')

 File "C:/Users/leng/Documents/Project/scrapNrequest.py", line 24, in scrap_article

   dict_url['text'] = get_text(article['url'])

 File "C:/Users/leng/Documents/Project/scrapNrequest.py", line 13, in get_text

   article.parse()

 File "C:\Users\leng\AppData\Local\Programs\Python\Python36-32\lib\site-packages\newspaper\article.py", line 185, in parse

   self.throw_if_not_downloaded_verbose()

 File "C:\Users\leng\AppData\Local\Programs\Python\Python36-32\lib\site-packages\newspaper\article.py", line 521, in throw_if_not_downloaded_verbose

   raise ArticleException()

newspaper.article.ArticleException

Process finished with exit code 1

**Comment by lengx03** [comment]
how to fix

**Comment by shifatul-i** [comment]
Fixed it using `sleep(SLEEP_TIME_IN_MILI_SEC)`, look at the source for more information
